---
title: "quality_of_life"
output:
  word_document: default
  html_document:
    df_print: paged
date: "2024-02-08"
---

#####Quality of Life in 19 Countries

####Import Data:
```{r}
dt<- read.csv("data4.csv")
row.names(dt)<- dt[,1]
dt<- dt[,-c(1)]
```


####Normalize Data
```{r}
dt.norm<- sapply(dt, scale)
row.names(dt.norm)<-row.names(dt)
dt.norm
```

####Find the Euclidean distance:
```{r}
dist.norm<- dist(dt.norm, method = "euclidean" )
```

####Form clusters (k=3)
```{r}
set.seed(100)
km<- kmeans(dt.norm,3)
km$cluster
```

####Centroids for Each Cluster
```{r}
km$centers
```


####Visualization of Clusters
```{r}

plot(c(0), xaxt = 'n', ylab = "", type = "b",
     ylim = c(min(km$centers), max(km$centers)), xlim = c(0, 8))

axis(1, at = c(1:7), labels = names(dt))  

for (i in 1:3) {
  line_color <- switch(i, "red", "purple", "pink", "black", "purple")
  lines(km$centers[i, ], lty = i, lwd = 3, col = line_color)
}

text(x = 0.5, y = km$centers[, 1], labels = paste("Cluster", 1:3))


```



